name: phabox2

channels:
  - defaults
  - conda-forge
  - bioconda

dependencies:
  - python >=3.8
  - biopython >=1.84
  - datasets >=3
  - kcounter >=0.1.1
  - fasttree >=2.1.11
  - mafft >=7.525
  - networkx >=3.4
  - numpy >=1.26
  - pandas >=2
  - prodigal-gv >=2.11.0
  - pyarrow >=16
  - pytorch >=2.4
  - scipy >=1.14
  - seaborn-base >=0.13.2
  - transformers >=4
  - blast >=2.16.0
  - diamond <=0.9.14
  - mcl >=22.282
  - accelerate >=1.0.1
