name: Python Package using Conda

on:
  pull_request:
    branches:
    - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # download scripts
        git clone https://github.com/KennthShang/PhaBOX.git
        cd PhaBOX
        python  -m pip install .
        cd ..
        # download database
        wget https://github.com/KennthShang/PhaBOX/releases/download/v2/example_contigs.fa
        wget https://github.com/KennthShang/PhaBOX/releases/download/v2/phabox_db_v2.zip
        unzip phabox_db_v2.zip  > /dev/null
        # run test
        phabox2 --task end_to_end --contigs example_contigs.fa -o end_to_end -d ../phabox_db_v2
        phabox2 --task phamer --contigs example_contigs.fa -o phamer -d ../phabox_db_v2
        phabox2 --task phagcn --contigs example_contigs.fa -o phagcn -d ../phabox_db_v2
        phabox2 --task phatyp --contigs example_contigs.fa -o phatyp -d ../phabox_db_v2
        phabox2 --task cherry --contigs example_contigs.fa -o cherry -d ../phabox_db_v2
        phabox2 --task contamination --contigs example_contigs.fa -o contamination -d ../phabox_db_v2
        phabox2 --task votu --contigs example_contigs.fa -o vout -d ../phabox_db_v2 --mode AAI
        phabox2 --task votu --contigs example_contigs.fa -o vout -d ../phabox_db_v2 --mode ANI
        phabox2 --task tree --contigs example_contigs.fa -o tree -d ../phabox_db_v2 --msa Y --tree N
        
